### ISSUE TITLE
Facing Issue when Running init.sh file

### ISSUE THREAD

**Issue by SaurabhSinghDev** [kudelskisecurity/fumblechain#6]
Getting Following error : 
Not able to setup

![image](https://user-images.githubusercontent.com/46048255/224236127-40d4ad3c-03dd-4c49-93e9-f37d88faa982.png)

**Comment by amietn** [comment]
Hello @SaurabhSinghDev . Thank you for using fumblechain.

Can you please explain which commands you executed to obtain this error?
This may help us reproduce it.

**Comment by SaurabhSinghDev** [comment]
@amietn  i was executing `./init_ctf.sh`  command when i faced this issue.

**Comment by SaurabhSinghDev** [comment]
I hope you are able to reproduce the error.

**Comment by enigma-solutions-qa** [comment]
I'm having the same issue - cannot install on ubuntu 22

**Comment by JaxkDev** [comment]
Reverting https://github.com/kudelskisecurity/fumblechain/commit/7ffa5335b3781ac6a20848b2a5016d7c3744b11b (#4) fixes this issue.

(fyi, trying 35.0.0 and latest, they didn't seem to need rust so may be able to remove that version constraint now.)

**Comment by JaxkDev** [comment]
```
┌──(kali㉿kali)-[~/fumblechain/src/fumblechain]
└─$ ./init_ctf.sh                      
=============================================
=                DISCLAIMER                 =
=============================================
When running this software on your own machine, you may expose yourself to attacks.
We cannot guarantee that the software is bug-free.
Upon starting the FumbleStore, various background services are started.
These services will listen for incoming connections on multiple TCP ports.
Proceed with caution and make sure your firewall rules are properly set.

*********************************************
*          Starting up FumbleStore          *
*********************************************
This process usually takes about 3 minutes.
Please wait...

[+] Building 1.9s (12/12) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 273B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         1.8s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [1/7] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c3   0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 9.05kB                                                                                          0.0s 
 => CACHED [2/7] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                             0.0s 
 => CACHED [3/7] COPY requirements.txt .                                                                                     0.0s 
 => CACHED [4/7] RUN pip install -r requirements.txt                                                                         0.0s 
 => CACHED [5/7] WORKDIR /opt/fumblechain                                                                                    0.0s 
 => CACHED [6/7] RUN mkdir volume                                                                                            0.0s 
 => CACHED [7/7] COPY . .                                                                                                    0.0s 
 => exporting to image                                                                                                       0.0s 
 => => exporting layers                                                                                                      0.0s 
 => => writing image sha256:a567bbacc0bbd85d962d6627116fa00d34cc9fad020e4126db5631a3dcbadb71                                 0.0s 
 => => naming to docker.io/library/fcgen:latest                                                                              0.0s 
Traceback (most recent call last):                                                                                                
  File "./gen_ctf_wallets.py", line 129, in <module>
    main()
  File "./gen_ctf_wallets.py", line 117, in main
    ch1_pubkeys = generate_challenge1_wallets(wallet_dir)
  File "./gen_ctf_wallets.py", line 68, in generate_challenge1_wallets
    ch1_wallet = generate_or_load_random_wallet("moneymaker.wallet", wallet_dir)
  File "./gen_ctf_wallets.py", line 53, in generate_or_load_random_wallet
    privkey = genkey.genkey()
  File "/opt/fumblechain/utils/genkey.py", line 10, in genkey
    w.create_keys()
  File "/opt/fumblechain/model/wallet.py", line 18, in create_keys
    self.skey, self.pkey = Crypt.generate_keypair()
  File "/opt/fumblechain/crypto/rsabased.py", line 24, in generate_keypair
    backend=default_backend()
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 117, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Error relocating /usr/local/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: FIPS_mode_set: symbol not found
ERROR: Couldn't find env file: /home/kali/fumblechain/src/fumblechain/gen/echoservice.env

=============================================
=                DISCLAIMER                 =
=============================================
When running this software on your own machine, you may expose yourself to attacks.
We cannot guarantee that the software is bug-free.
Upon starting the FumbleStore, various background services are started.
These services will listen for incoming connections on multiple TCP ports.
Proceed with caution and make sure your firewall rules are properly set.

*********************************************
*         Accessing the FumbleStore         *
*********************************************

The FumbleStore should now be up and running at http://localhost:20801

To shutdown all FumbleChain services, type:
docker-compose down


                                                                                                                                  
┌──(kali㉿kali)-[~/fumblechain/src/fumblechain]
└─$ ls
api        daemon.sh           explorer        gen_ctf_wallets.py       init_ctf.sh  README            store
cli.py     docker              fc-docker.sh    genesis.json             __init__.py  requirements.txt  templates
crypto     docker-compose.yml  fumblestore.py  gen_flask_secret_key.py  model        scli.py           test.py
daemon.py  Dockerfile          gen             gen.sh                   net          static            utils
                                                                                                                                  
┌──(kali㉿kali)-[~/fumblechain/src/fumblechain]
└─$ vi requirements.txt 
                                                                                                                                  
┌──(kali㉿kali)-[~/fumblechain/src/fumblechain]
└─$ ./init_ctf.sh         
=============================================
=                DISCLAIMER                 =
=============================================
When running this software on your own machine, you may expose yourself to attacks.
We cannot guarantee that the software is bug-free.
Upon starting the FumbleStore, various background services are started.
These services will listen for incoming connections on multiple TCP ports.
Proceed with caution and make sure your firewall rules are properly set.

*********************************************
*          Starting up FumbleStore          *
*********************************************
This process usually takes about 3 minutes.
Please wait...

[+] Building 18.2s (12/12) FINISHED                                                                                docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 273B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.7s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [1/7] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c3   0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 9.23kB                                                                                          0.0s 
 => CACHED [2/7] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                             0.0s 
 => [3/7] COPY requirements.txt .                                                                                            0.1s 
 => [4/7] RUN pip install -r requirements.txt                                                                               16.4s 
 => [5/7] WORKDIR /opt/fumblechain                                                                                           0.1s 
 => [6/7] RUN mkdir volume                                                                                                   0.3s 
 => [7/7] COPY . .                                                                                                           0.1s 
 => exporting to image                                                                                                       0.5s 
 => => exporting layers                                                                                                      0.4s 
 => => writing image sha256:df5640a0a5293852f8c590ba8b0065c4eed0eaf6d4dd2beb36e86f21e423439c                                 0.0s 
 => => naming to docker.io/library/fcgen:latest                                                                              0.0s
/opt/fumblechain/crypto/rsabased.py:7: CryptographyDeprecationWarning: Python 3.7 is no longer supported by the Python core team and support for it is deprecated in cryptography. A future release of cryptography will remove support for Python 3.7.
  from cryptography.exceptions import InvalidSignature
Creating network "fumblechain_default" with the default driver
Building fumblestore
[+] Building 6.3s (37/37) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 1.96kB                                                                                       0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.6s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [internal] load build context                                                                                            0.2s 
 => => transferring context: 8.24MB                                                                                          0.2s
 => [targz  1/13] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff002  0.0s
 => CACHED [targz  2/13] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                     0.0s 
 => [targz  3/13] WORKDIR /tmp/fumblechain                                                                                   0.2s 
 => [targz  4/13] COPY . .                                                                                                   0.2s
 => CACHED [fumblestore  3/12] COPY src/fumblechain/requirements.txt .                                                       0.0s 
 => CACHED [fumblestore  4/12] RUN pip install -r requirements.txt                                                           0.0s 
 => CACHED [fumblestore  5/12] WORKDIR /opt/fumblechain                                                                      0.0s 
 => [fumblestore  6/12] COPY . .                                                                                             0.2s 
 => [targz  5/13] RUN git checkout -f master                                                                                 0.7s
 => [targz-ch4  5/13] RUN git checkout -f challenge4                                                                         0.7s
 => [fumblestore  7/12] WORKDIR src/fumblechain                                                                              0.2s
 => [fumblestore  8/12] RUN mkdir volume                                                                                     0.7s
 => [targz  6/13] RUN git clean -fdx                                                                                         0.7s
 => [targz-ch4  6/13] RUN git clean -fdx                                                                                     1.0s
 => [fumblestore  9/12] RUN mkdir -p static/downloads                                                                        0.8s 
 => [targz  7/13] WORKDIR src                                                                                                0.3s 
 => [targz  8/13] COPY src/fumblechain/daemon.sh fumblechain/                                                                0.1s
 => [targz-ch4  7/13] WORKDIR src                                                                                            0.2s
 => [targz  9/13] COPY src/fumblechain/fc-docker.sh fumblechain/                                                             0.1s
 => [targz-ch4  8/13] COPY src/fumblechain/daemon.sh fumblechain/                                                            0.1s 
 => [targz 10/13] COPY src/fumblechain/gen/ctf_wallet_addresses.bash fumblechain/                                            0.1s
 => [targz-ch4  9/13] COPY src/fumblechain/fc-docker.sh fumblechain/                                                         0.1s 
 => [targz 11/13] COPY src/fumblechain/Dockerfile fumblechain/                                                               0.1s
 => [targz-ch4 10/13] COPY src/fumblechain/gen/ctf_wallet_addresses.bash fumblechain/                                        0.1s
 => [targz 12/13] RUN tar czvf fumblechain.tar.gz fumblechain                                                                0.6s 
 => [targz-ch4 11/13] COPY src/fumblechain/Dockerfile fumblechain/                                                           0.1s
 => [targz-ch4 12/13] RUN tar czvf fumblechain.tar.gz fumblechain                                                            0.5s 
 => [targz 13/13] RUN cp fumblechain.tar.gz /tmp/fumblechain/fumblechain.tar.gz                                              0.5s
 => [targz-ch4 13/13] RUN cp fumblechain.tar.gz /tmp/fumblechain/fumblechain-ch4.tar.gz                                      0.5s 
 => [fumblestore 10/12] COPY --from=targz /tmp/fumblechain/fumblechain.tar.gz static/downloads/                              0.1s 
 => [fumblestore 11/12] COPY --from=targz-ch4 /tmp/fumblechain/fumblechain-ch4.tar.gz static/downloads/                      0.1s 
 => [fumblestore 12/12] RUN pip install gunicorn                                                                             1.5s 
 => exporting to image                                                                                                       0.2s 
 => => exporting layers                                                                                                      0.2s 
 => => writing image sha256:22ff5c074106e95128895c1dae2518f2b96919baf1b3c9bfdbec3310bdafaa69                                 0.0s 
 => => naming to docker.io/library/fumblechain_fumblestore                                                                   0.0s 
Building moneymaker                                                                                                               
[+] Building 3.8s (17/17) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 515B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.3s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [ 1/12] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c  0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 15.23kB                                                                                         0.0s 
 => CACHED [ 2/12] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                           0.0s 
 => CACHED [ 3/12] COPY src/fumblechain/requirements.txt .                                                                   0.0s 
 => CACHED [ 4/12] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [ 5/12] WORKDIR /opt/fumblechain                                                                                  0.0s 
 => CACHED [ 6/12] COPY . .                                                                                                  0.0s 
 => [ 7/12] RUN git checkout -f challenge1                                                                                   0.3s 
 => [ 8/12] RUN git clean -fdx                                                                                               0.3s
 => [ 9/12] WORKDIR src/fumblechain                                                                                          0.1s
 => [10/12] RUN pip install -r requirements.txt                                                                              0.9s
 => [11/12] COPY src/fumblechain/gen/wallets ./wallets                                                                       0.1s 
 => [12/12] RUN pip install gunicorn                                                                                         1.4s 
 => exporting to image                                                                                                       0.2s 
 => => exporting layers                                                                                                      0.1s 
 => => writing image sha256:64c75f31c279927aa844827e629136ea6f66a2304f4ea690e7302b39d8b17f64                                 0.0s 
 => => naming to docker.io/library/fumblechain_moneymaker                                                                    0.0s 
Building mainnet-node                                                                                                             
[+] Building 0.5s (15/15) FINISHED                                                                                 docker:default 
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 422B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.3s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [ 1/10] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c  0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 15.23kB                                                                                         0.0s 
 => CACHED [ 2/10] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                           0.0s 
 => CACHED [ 3/10] COPY src/fumblechain/requirements.txt .                                                                   0.0s 
 => CACHED [ 4/10] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [ 5/10] WORKDIR /opt/fumblechain                                                                                  0.0s 
 => CACHED [ 6/10] COPY . .                                                                                                  0.0s 
 => CACHED [ 7/10] RUN git checkout -f challenge1                                                                            0.0s 
 => CACHED [ 8/10] RUN git clean -fdx                                                                                        0.0s 
 => CACHED [ 9/10] WORKDIR src/fumblechain                                                                                   0.0s 
 => CACHED [10/10] RUN pip install -r requirements.txt                                                                       0.0s 
 => exporting to image                                                                                                       0.0s 
 => => exporting layers                                                                                                      0.0s 
 => => writing image sha256:b5638afb904bc5f076ac70734f34f21ace9557a8034c531d5ae6de4b95912da0                                 0.0s 
 => => naming to docker.io/library/fumblechain_mainnet-node                                                                  0.0s 
Building testnet-node                                                                                                             
[+] Building 0.3s (15/15) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 496B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.2s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [ 1/10] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c  0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 15.23kB                                                                                         0.0s 
 => CACHED [ 2/10] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                           0.0s 
 => CACHED [ 3/10] COPY src/fumblechain/requirements.txt .                                                                   0.0s 
 => CACHED [ 4/10] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [ 5/10] WORKDIR /opt/fumblechain                                                                                  0.0s 
 => CACHED [ 6/10] COPY . .                                                                                                  0.0s 
 => CACHED [ 7/10] RUN git checkout -f challenge1                                                                            0.0s 
 => CACHED [ 8/10] RUN git clean -fdx                                                                                        0.0s 
 => CACHED [ 9/10] WORKDIR src/fumblechain                                                                                   0.0s 
 => CACHED [10/10] RUN pip install -r requirements.txt                                                                       0.0s 
 => exporting to image                                                                                                       0.0s 
 => => exporting layers                                                                                                      0.0s 
 => => writing image sha256:0b1cf825a1cd104ba8e107a3732fa210de883e8904a3983808eef442305db0f8                                 0.0s 
 => => naming to docker.io/library/fumblechain_testnet-node                                                                  0.0s 
Building mainnet2-node                                                                                                            
[+] Building 2.3s (16/16) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 427B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.2s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [ 1/11] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c  0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 15.23kB                                                                                         0.0s 
 => CACHED [ 2/11] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                           0.0s 
 => CACHED [ 3/11] COPY src/fumblechain/requirements.txt .                                                                   0.0s 
 => CACHED [ 4/11] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [ 5/11] WORKDIR /opt/fumblechain                                                                                  0.0s 
 => CACHED [ 6/11] COPY . .                                                                                                  0.0s 
 => [ 7/11] RUN git checkout -f challenge2                                                                                   0.3s 
 => [ 8/11] RUN git clean -fdx                                                                                               0.4s
 => [ 9/11] WORKDIR src/fumblechain                                                                                          0.1s
 => [10/11] RUN pip install -r requirements.txt                                                                              0.9s
 => [11/11] COPY src/fumblechain/gen/wallets ./wallets                                                                       0.1s 
 => exporting to image                                                                                                       0.2s 
 => => exporting layers                                                                                                      0.1s 
 => => writing image sha256:f42a0302ad1688e38ab964096fa6cf81d991743c1c18a873f19d0000564e8239                                 0.0s 
 => => naming to docker.io/library/fumblechain_mainnet2-node                                                                 0.0s 
Building mainnet3-node                                                                                                            
[+] Building 2.3s (16/16) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 494B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.2s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [ 1/11] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c  0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 15.23kB                                                                                         0.0s 
 => CACHED [ 2/11] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                           0.0s 
 => CACHED [ 3/11] COPY src/fumblechain/requirements.txt .                                                                   0.0s 
 => CACHED [ 4/11] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [ 5/11] WORKDIR /opt/fumblechain                                                                                  0.0s 
 => CACHED [ 6/11] COPY . .                                                                                                  0.0s 
 => [ 7/11] RUN git checkout -f challenge3                                                                                   0.4s 
 => [ 8/11] RUN git clean -fdx                                                                                               0.3s 
 => [ 9/11] WORKDIR src/fumblechain                                                                                          0.1s
 => [10/11] RUN pip install -r requirements.txt                                                                              0.9s
 => [11/11] COPY src/fumblechain/gen/wallets ./wallets                                                                       0.1s 
 => exporting to image                                                                                                       0.1s 
 => => exporting layers                                                                                                      0.1s 
 => => writing image sha256:c93498381d2cd52fc8e103c2bfaa70b79645bf74ef1643532fcad2f6c0586123                                 0.0s 
 => => naming to docker.io/library/fumblechain_mainnet3-node                                                                 0.0s 
Building mainnet4-node                                                                                                            
[+] Building 2.4s (16/16) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 494B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.2s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [ 1/11] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c  0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 15.23kB                                                                                         0.0s 
 => CACHED [ 2/11] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                           0.0s 
 => CACHED [ 3/11] COPY src/fumblechain/requirements.txt .                                                                   0.0s 
 => CACHED [ 4/11] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [ 5/11] WORKDIR /opt/fumblechain                                                                                  0.0s 
 => CACHED [ 6/11] COPY . .                                                                                                  0.0s 
 => [ 7/11] RUN git checkout -f challenge4                                                                                   0.4s 
 => [ 8/11] RUN git clean -fdx                                                                                               0.3s
 => [ 9/11] WORKDIR src/fumblechain                                                                                          0.1s
 => [10/11] RUN pip install -r requirements.txt                                                                              1.0s
 => [11/11] COPY src/fumblechain/gen/wallets ./wallets                                                                       0.1s 
 => exporting to image                                                                                                       0.1s 
 => => exporting layers                                                                                                      0.1s 
 => => writing image sha256:b44876c46c6745ea50f5623b9dc63ba1510d37adacb4ffa38f9895b45d356118                                 0.0s 
 => => naming to docker.io/library/fumblechain_mainnet4-node                                                                 0.0s 
Building echoservice                                                                                                              
[+] Building 0.5s (16/16) FINISHED                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 431B                                                                                         0.0s 
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                         0.3s 
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s 
 => [ 1/11] FROM docker.io/library/python:3.7-alpine@sha256:f3d31c8677d03f0b3c724446077f229a6ce9d3ac430f5c08cd7dff00292048c  0.0s 
 => [internal] load build context                                                                                            0.0s 
 => => transferring context: 15.23kB                                                                                         0.0s 
 => CACHED [ 2/11] RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git                           0.0s 
 => CACHED [ 3/11] COPY src/fumblechain/requirements.txt .                                                                   0.0s 
 => CACHED [ 4/11] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [ 5/11] WORKDIR /opt/fumblechain                                                                                  0.0s 
 => CACHED [ 6/11] COPY . .                                                                                                  0.0s 
 => CACHED [ 7/11] RUN git checkout -f challenge3                                                                            0.0s 
 => CACHED [ 8/11] RUN git clean -fdx                                                                                        0.0s 
 => CACHED [ 9/11] WORKDIR src/fumblechain                                                                                   0.0s 
 => CACHED [10/11] RUN pip install -r requirements.txt                                                                       0.0s 
 => CACHED [11/11] COPY src/fumblechain/gen/wallets ./wallets                                                                0.0s 
 => exporting to image                                                                                                       0.0s 
 => => exporting layers                                                                                                      0.0s 
 => => writing image sha256:acafe6da5a2d643c58bd26aee5b7eb441569e633dbfcf10f6db8e58e689fad50                                 0.0s 
 => => naming to docker.io/library/fumblechain_echoservice                                                                   0.0s 
Creating fumblechain_mainnet3-node_1 ... done
Creating fumblechain_fumblestore_1   ... done
Creating fumblechain_testnet-node_1  ... done
Creating fumblechain_echoservice_1   ... done
Creating fumblechain_moneymaker_1    ... done
Creating fumblechain_mainnet4-node_1 ... done
Creating fumblechain_mainnet-node_1  ... done
Creating fumblechain_mainnet2-node_1 ... done

=============================================
=                DISCLAIMER                 =
=============================================
When running this software on your own machine, you may expose yourself to attacks.
We cannot guarantee that the software is bug-free.
Upon starting the FumbleStore, various background services are started.
These services will listen for incoming connections on multiple TCP ports.
Proceed with caution and make sure your firewall rules are properly set.

*********************************************
*         Accessing the FumbleStore         *
*********************************************

The FumbleStore should now be up and running at http://localhost:20801

To shutdown all FumbleChain services, type:
docker-compose down


                                                                                                                                  
┌──(kali㉿kali)-[~/fumblechain/src/fumblechain]
└─$
```
